name: overwatch_mobile
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  dio: ^5.7.0
  ffi: ^2.1.3
  google_fonts: ^6.2.1
  intl: ^0.19.0
  dio_smart_retry: ^6.0.0
  equatable: ^2.0.7
  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  crypto: ^3.0.7
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.3
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
